import Head from 'next/head';
import Header from '../components/Header/Header';
import Skills from '../components/Skills/Skills';
import Start from '../components/Start/Start';
import Work from '../components/Work/Work';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Header/>
        <Start/>
        <Skills/>
        <Work/>
      </div>

    </div>
  )
}
